name: Cronjob

# Run every hour on the hour.
# `actions` is the name of my prototyping branch, so also run this job when I push there.
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - actions

jobs:
  build-popular-package:
    name: build-popular-package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: find crate to build
        id: find_crate
        env:
          SEMATEXT_API_KEY: ${{ secrets.SEMATEXT_API_KEY }}
          SEMATEXT_APP_TOKEN: ${{ secrets.SEMATEXT_APP_TOKEN }}
        run: |
          set -euo pipefail
          touch .env
          # This script will do the `::set-output` dance for us
          ./next-unbuilt-package.sh
      - name: build package
        env:
          TEMPDIR: /tmp/built.d/
        run: |
          set -euo pipefail
          mkdir -p "$TEMPDIR"
          crate="${{steps.find_crate.outputs.crate_to_build}}"
          ./build-version.sh "$crate"
      - name: upload package
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          TEMPDIR: /tmp/built.d/
        run: |
          set -euo pipefail
          mkdir -p "$TEMPDIR"
          crate="${{steps.find_crate.outputs.crate_to_build}}"
          version="${{steps.find_crate.outputs.version_to_build}}"
          arch="${{steps.find_crate.outputs.arch_to_build}}"
          ./upload-version.sh "$crate" "$version" "$arch"
