name: Cronjob

# Run every hour on the hour.
# `actions` is the name of my prototyping branch, so also run this job when I push there.
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - actions

jobs:
  build-popular-package:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Trigger Package Build
        id: find_crate
        env:
          SEMATEXT_API_KEY: ${{ secrets.SEMATEXT_API_KEY }}
          SEMATEXT_APP_TOKEN: ${{ secrets.SEMATEXT_APP_TOKEN }}
        run: |
          set -euo pipefail
          touch .env
          ./trigger-package-build.sh
