name: Self-Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches-ignore:
      - actions

jobs:
  self-build:
    name: Self-Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        # FIXME: add cross-compilation targets to this matrix somehow
        os: [macos-latest, ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build Thyself
        run: |
          set -euxo pipefail
          touch .env
          VERSION=$(
            curl \
              --user-agent "cargo-quickinstall build pipeline (alsuren@gmail.com)" \
              --fail "https://crates.io/api/v1/crates/cargo-quickinstall" \
              | jq -r .versions[0].num
          )
          env ALWAYS_BUILD=1 VERSION=$VERSION TARGET_ARCH=TARGET_ARCH=$(rustc --version --verbose | sed -n 's/host: //p') ./build-version.sh cargo-quickinstall
      - name: Install Thyself
        run: cargo install --path cargo-quickinstall
      - name: Install Thyself with Thyself (or fallback to sensei on windows)
        run: cargo quickinstall cargo-quickinstall || cargo quickinstall sensei
