name: Self-Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches-ignore:
      - actions

jobs:
  self-build:
    name: Self-Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build Thyself
        env:
          SEMATEXT_API_KEY: ${{ secrets.SEMATEXT_API_KEY }}
          SEMATEXT_APP_TOKEN: ${{ secrets.SEMATEXT_APP_TOKEN }}
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: |
          set -euo pipefail
          touch .env
          ./build-version.sh cargo-quickinstall
          # FIXME: re-enable uploading code here.
      - name: Install Thyself
        run: cargo install --path cargo-quickinstall
      - name: Install Thyself with Thyself (or fallback to sensei on windows)
        run: cargo quickinstall cargo-quickinstall || cargo quickinstall sensei
