# Coding format checker and test runner.
name: Automated tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Fetch source
        uses: actions/checkout@v2

      - name: Lint
        run: cargo fmt --check

  test:
    name: Test runner
    runs-on: ubuntu-latest

    steps:
      # TODO: actions/cache@v2?
      - name: Fetch source
        uses: actions/checkout@v2

      - name: Run test
        run: cargo test
